language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
  yarn: true
script:
  - npm run build
  - npm test
  - npm test --coverage && cat ./coverage/lcov.info | coveralls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master